// Generated by Wrangler on Tue Aug 06 2024 21:03:17 GMT+1200 (New Zealand Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
